### ISSUE TITLE
Speedway CLI Schema Creation Breaks on Terminal

### ISSUE THREAD

**Issue by mihirKachroo** [sonr-io/speedway#149]
* **Version**: v1.0.3-beta.1 
* **Platform**: MacOS
* **Subsystem**:

#### Issue description
Speedway CLI schema creation breaks on integrated VSCode terminal, iterm2 and Apple terminal.

#### Steps to reproduce the issue

1. Open a terminal 
2. cd into speedway/cmd/speedway-cli/
3. Run `go run main.go schema create`
4. Add label and start typing in a long list of labels:types
5. Witness

#### What's the expected result?

- Schema gets created

#### What's the actual result?

- New line of the command is printed every time a character is added to the list after a certain string size (which i assume is relative to the width of the terminal) is passed

#### Additional details / screenshot

- <img width="721" alt="Screen Shot 2022-09-17 at 6 09 26 PM" src="https://user-images.githubusercontent.com/60433268/190877940-8ca71843-0fdc-4638-985b-25e4245d7db2.png">

**Comment by 6missedcalls** [comment]
Associated PR: https://github.com/sonr-io/speedway/pull/167
